caches:
  1928_cache:
    grids: [mercator]
    sources: [1928_source]
  1953_cache:
    grids: [mercator]
    sources: [1953_source]
  2015_cir_cache:
    grids: [mercator]
    sources: [2015_cir_source]
  2016_cir_cache:
    grids: [mercator]
    sources: [2016_cir_source]
  2018_cache:
    grids: [mercator]
    sources: [2018_source]
  alkis_30_cache:
    grids: [mercator]
    sources: [alkis_30_source]
  atkis_dgm_1_cache:
    grids: [mercator]
    sources: [atkis_dgm_1_source]
  atkis_dgm_3_cache:
    grids: [mercator]
    sources: [atkis_dgm_3_source]
  atkis_dom_cache:
    grids: [mercator]
    sources: [atkis_dom_source]
  zoom_cache:
    grids: [mercator]
    sources: [zoom_source]
globals: {}
grids:
  mercator: {base: GLOBAL_MERCATOR}
layers:
- name: zoom
  sources: [zoom_cache]
  title: Berlin Zoom
- name: alkis_30
  sources: [alkis_30_cache]
  title: ALKIS Berlin (Amtliches Liegenschaftskatasterinformationssystem)
- name: atkis_dgm_1
  sources: [atkis_dgm_1_cache]
  title: !!python/str "ATKIS\xAE DGM - Digitales Gel\xE4ndemodell"
- name: atkis_dgm_3
  sources: [atkis_dgm_3_cache]
  title: !!python/str "ATKIS\xAE DGM - Digitales Gel\xE4ndemodell"
- name: atkis_dom
  sources: [atkis_dom_cache]
  title: !!python/str "ATKIS\xAE DOM - Digitales Oberfl\xE4chenmodell"
- name: '2018'
  sources: [2018_cache]
  title: Digitale farbige Orthophotos 2018 (DOP20RGB)
- name: 2016_cir
  sources: [2016_cir_cache]
  title: Digitale Color-Infrarot-Orthophotos 2016 (DOP20CIR)
- name: 2015_cir
  sources: [2015_cir_cache]
  title: Digitale Color-Infrarot-Orthophotos 2015 (DOP20CIR)
- name: '1953'
  sources: [1953_cache]
  title: Berlin 1953
- name: '1928'
  sources: [1928_cache]
  title: Berlin 1928
services:
  demo: {}
  tms: {origin: nw, use_grid_names: true}
sources:
  1928_source:
    req: {format: png, layers: '0', style: default, transparent: true, url: 'https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild1928'}
    supported_srs: ['EPSG:25833']
    type: wms
    wms_opts: {version: 1.3.0}
  1953_source:
    req: {format: png, layers: '0', style: default, transparent: true, url: 'https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild1953'}
    supported_srs: ['EPSG:25833']
    type: wms
    wms_opts: {version: 1.3.0}
  2015_cir_source:
    req: {format: png, layers: '0', style: default, transparent: true, url: 'https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2015_cir'}
    supported_srs: ['EPSG:25833']
    type: wms
    wms_opts: {version: 1.3.0}
  2016_cir_source:
    req: {format: png, layers: '0', style: default, transparent: true, url: 'https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2016_cir'}
    supported_srs: ['EPSG:25833']
    type: wms
    wms_opts: {version: 1.3.0}
  2018_source:
    req: {format: png, layers: '0', style: default, transparent: true, url: 'https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2018_rgb'}
    supported_srs: ['EPSG:25833']
    type: wms
    wms_opts: {version: 1.3.0}
  alkis_30_source:
    req: {format: png, layers: '30', style: default, transparent: true, url: 'https://fbinter.stadt-berlin.de/fb/wms/senstadt/wmsk_alkis'}
    supported_srs: ['EPSG:25833']
    type: wms
    wms_opts: {version: 1.3.0}
  atkis_dgm_1_source:
    req: {format: png, layers: '1', style: default, transparent: true, url: 'https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_dgm1'}
    supported_srs: ['EPSG:25833']
    type: wms
    wms_opts: {version: 1.3.0}
  atkis_dgm_3_source:
    req: {format: png, layers: '3', style: default, transparent: true, url: 'https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_dgm1'}
    supported_srs: ['EPSG:25833']
    type: wms
    wms_opts: {version: 1.3.0}
  atkis_dom_source:
    req: {format: png, layers: '1', style: default, transparent: true, url: 'https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_dom'}
    supported_srs: ['EPSG:25833']
    type: wms
    wms_opts: {version: 1.3.0}
  zoom_source:
    req: {format: png, layers: '0', style: default, transparent: true, url: 'https://fbinter.stadt-berlin.de/fb/wms/senstadt/berlinzoom'}
    supported_srs: ['EPSG:25833']
    type: wms
    wms_opts: {version: 1.3.0}
