- name: topplus_web
  title: TopPlusOpen web
  url: http://sgx.geodatenzentrum.de/wms_topplus_open
  layer: web
  transparent: false

- name: topplus_p5
  title: TopPlusOpen
  url: http://sgx.geodatenzentrum.de/wms_topplus_open
  layer: p5
  transparent: false

- name: zoom
  title: Berlin Zoom
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/berlinzoom
  layer: 0
  transparent: false

- name: alkis_30
  title: ALKIS Berlin (Amtliches Liegenschaftskatasterinformationssystem)
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/wmsk_alkis
  layer: 30
  transparent: false

- name: atkis_dgm_1
  title: ATKIS® DGM - Digitales Geländemodell
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_dgm1
  layer: 1
  transparent: true

- name: atkis_dgm_3
  title: ATKIS® DGM - Digitales Geländemodell
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_dgm1
  layer: 3
  transparent: true

- name: atkis_dom
  title: ATKIS® DOM - Digitales Oberflächenmodell
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_dom
  layer: 1
  transparent: false

- name: '2019'
  title: Digitale farbige Orthophotos 2019 (DOP20RGB)
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2019_rgb
  layer: 0
  transparent: false

- name: '2018'
  title: Digitale farbige Orthophotos 2018 (DOP20RGB)
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2018_rgb
  layer: 0
  transparent: false

- name: 2016_cir
  title: Digitale Color-Infrarot-Orthophotos 2016 (DOP20CIR)
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2016_cir
  layer: 0
  transparent: false

- name: 2015_cir
  title: Digitale Color-Infrarot-Orthophotos 2015 (DOP20CIR)
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2015_cir
  layer: 0
  transparent: false

- name: '2013'
  title: Digitale farbige Trueorthophotos 2013
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2013
  layer: 0
  transparent: false

- name: '1953'
  title: Berlin 1953
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild1953
  layer: 0
  transparent: false

- name: '1928'
  title: Berlin 1928
  url: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild1928
  layer: 0
  transparent: false
